name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: EnvironmentalMonitoringReciever.sln
     
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    # Restore paages, MSBUild the app, run the app
    - name: Build the App
      shell: cmd
      run: call build.bat 

    # Run the app
    - name: Run the App
      shell: cmd
      run: call run.bat
