name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: EnvironmentalMonitoringReciever.sln
     
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
      
   # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    # Restore paages, MSBUild the app, run the app
    - name: Build the App
      shell: cmd
      run: call build.bat 

    # Run the app
    - name: Run the App
      shell: cmd
      run: call run.bat
